name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - r-base=4.0
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - pip
  - pip:
    - matplotlib
    - scikit-learn
    - statsmodels
    - seaborn
